---
- name: Install and configure Apache web server
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache
      yum:
        update_cache: yes

    - name: Install Apache2
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd

        state: started
        enabled: yes

    - name: Deploy custom website homepage
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

